---
#tasks file for DOCKER_ROLE
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items: '{{ liste }}'

- name: Install yum-utils
  shell: 'sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common'

- name: dl stable repository
  shell: 'sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

- name: set up stable repo
  shell: 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

- name: update apt-get  
  shell: 'sudo apt-get update'

- name: install docker engine
  shell: 'sudo apt-get -y install docker-ce docker-ce-cli containerd.io'

  notify: start docker
